# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MercadoLibreTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'
  pod 'NVActivityIndicatorView', '4.6.1'

  target 'MercadoLibreTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MercadoLibreTestUITests' do
    # Pods for testing
  end

end
